# Generated by Django 5.2.3 on 2025-07-01 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tipo",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "tipo_primario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Tipo_primario",
                        to="api_rest.tipo",
                    ),
                ),
                (
                    "tipo_secundario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Tipo_secundario",
                        to="api_rest.tipo",
                    ),
                ),
            ],
        ),
    ]
