# Generated by Django 5.2.3 on 2025-07-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="tipo_secundario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Tipo_secundario",
                to="api_rest.tipo",
            ),
        ),
    ]
